name = "worker"
main = "src/index.ts"
compatibility_date = "2026-07-17"

[build]
command = ""

[[d1_databases]]
binding = "DB"
database_name = "temp_email_db"
database_id = "29ed2625-d4e0-4e9f-aa29-b08bf38f02f4"

[vars]
DOMAINS = "cwxing.top"
ADMIN_PASSWORDS = "123456"
